# Operator Estimation

In [1]:
import numpy as np
from pyquil import Program, get_qc
from pyquil.gates import *
qc = get_qc('2q-qvm', noisy=True)

/home/kylegulshen/anaconda3/lib/python3.6/site-packages/rpcq/messages.py:314: UserWarning: Message RPCReply ignoring unexpected keyword arguments: warnings.
  "{}.").format(self.__class__.__name__, ", ".join(kwargs.keys())))


## Construct a `ObservablesExperiment` and turn it into a list of `Programs`


In [2]:
from pyquil.paulis import *
from forest.benchmarking.operator_estimation import ExperimentSetting, plusX, ObservablesExperiment, generate_experiment_programs
q = 0
# make ExperimentSettings for tomographing the plus state
expt_settings = [ExperimentSetting(plusX(q), pt) for pt in [sX(q), sY(q), sZ(q)]]
print('ExperimentSettings:\n==================\n',expt_settings,'\n')

# make an ObservablesExperiment
obs_expt = ObservablesExperiment(expt_settings, program=Program())
print('ObservablesExperiment:\n======================\n',obs_expt,'\n')

# convert it to a list of programs and a list of qubits for each program
expt_progs, qubits = generate_experiment_programs(obs_expt)
print('Programs and Qubits:\n======================\n')
for prog, qs in zip(expt_progs, qubits):
    print(prog, qs)


ExperimentSettings:
 [ExperimentSetting[X0_0→(1+0j)*X0], ExperimentSetting[X0_0→(1+0j)*Y0], ExperimentSetting[X0_0→(1+0j)*Z0]] 

ObservablesExperiment:
 
0: X0_0→(1+0j)*X0
1: X0_0→(1+0j)*Y0
2: X0_0→(1+0j)*Z0 

Programs and Qubits:

RX(pi/2) 0
RZ(pi/2) 0
RX(-pi/2) 0
RX(pi/2) 0
RZ(-pi/2) 0
RX(-pi/2) 0
 [0]
RX(pi/2) 0
RZ(pi/2) 0
RX(-pi/2) 0
RX(pi/2) 0
 [0]
RX(pi/2) 0
RZ(pi/2) 0
RX(-pi/2) 0
 [0]


## At this point we can run directly or first symmetrize

## 1) run programs directly

In [3]:
from forest.benchmarking.operator_estimation import _measure_bitstrings
# this is a simple wrapper that adds measure instructions for each qubit in qubits and runs each program.
results = _measure_bitstrings(qc, expt_progs, qubits, num_shots=5)
for bits in results:
    print(bits)

[[0]
 [0]
 [0]
 [0]
 [0]]
[[1]
 [1]
 [1]
 [1]
 [1]]
[[1]
 [0]
 [1]
 [0]
 [0]]


## 2) First symmetrize, then run

A symmetrization method should return  
1. a list of programs 
2. a list of measurement qubits associated with each program
3. a list of bits/bools indicating which qubits where flipped before measurement for each program
4. a list of ints indicating the group of results to which each program's outputs should be re-assigned after correction

In [4]:
from forest.benchmarking.operator_estimation import exhaustive_symmetrization, consolidate_symmetrization_outputs
symm_progs, symm_qs, flip_arrays, groups = exhaustive_symmetrization(expt_progs, qubits)
print('2 symmetrized programs for each original:\n======================\n')
for prog in symm_progs:
    print(prog)

# now these programs can be run as above
results = _measure_bitstrings(qc, symm_progs, symm_qs, num_shots=5)

# we now need to consolidate these results using the information in flip_arrays and groups 
results = consolidate_symmetrization_outputs(results, flip_arrays, groups)

print('After consolidating we have twice the number of (symmetrized) shots as above:\n======================\n')
# we now have twice the number of symmetrized shots
for bits in results:
    print(bits)

2 symmetrized programs for each original:

RX(pi/2) 0
RZ(pi/2) 0
RX(-pi/2) 0
RX(pi/2) 0
RZ(-pi/2) 0
RX(-pi/2) 0

RX(pi/2) 0
RZ(pi/2) 0
RX(-pi/2) 0
RX(pi/2) 0
RZ(-pi/2) 0
RX(-pi/2) 0
RX(pi) 0

RX(pi/2) 0
RZ(pi/2) 0
RX(-pi/2) 0
RX(pi/2) 0

RX(pi/2) 0
RZ(pi/2) 0
RX(-pi/2) 0
RX(pi/2) 0
RX(pi) 0

RX(pi/2) 0
RZ(pi/2) 0
RX(-pi/2) 0

RX(pi/2) 0
RZ(pi/2) 0
RX(-pi/2) 0
RX(pi) 0

After consolidating we have twice the number of (symmetrized) shots as above:

[[1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]]
[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]]
[[1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]]


## Now we can translate our bitarray shots into ExperimentResults with expectation values

In [5]:
from forest.benchmarking.operator_estimation import shots_to_obs_moments, ExperimentResult

expt_results_as_obs = []
# we use the settings from the ObservableExperiment to label our results
for bitarray, meas_qs, settings in zip(results, qubits, obs_expt):
    # settings is a list of settings run simultaneously for a given program;
    # in our case, we just had one setting per program so this isn't strictly uncessary
    for setting in settings:
        observable = setting.observable # get the PauliTerm
        
        # Obtain statistics from result of experiment
        obs_mean, obs_var = shots_to_obs_moments(bitarray, meas_qs, observable)
        
        expt_results_as_obs.append(ExperimentResult(setting, obs_mean, std_err = np.sqrt(obs_var),
                                                    total_counts = len(bitarray)))

for res in expt_results_as_obs:
    print(res)

X0_0→(1+0j)*X0: 0.4 +- 0.28982753492378877
X0_0→(1+0j)*Y0: -0.4 +- 0.28982753492378877
X0_0→(1+0j)*Z0: 0.2 +- 0.30983866769659335


## All of the above is wrapped in a convenience function estimate_observables

In [6]:
from forest.benchmarking.operator_estimation import estimate_observables

for res in estimate_observables(qc, obs_expt, num_shots=50, symmetrization_method = exhaustive_symmetrization):
    print(res)


X0_0→(1+0j)*X0: 0.92 +- 0.039191835884530846
X0_0→(1+0j)*Y0: 0.16 +- 0.09871170143402452
X0_0→(1+0j)*Z0: 0.02 +- 0.09997999799959989


## Finally after obtaining our results we can choose to calibrate our observables

This uses essentially the same workflow as above except that the programs are generated for each observable via 
`get_calibration_program`. I'll only demonstrate the convience wrapper below.

In [9]:
from forest.benchmarking.operator_estimation import calibrate_observable_estimates

for cal_res in calibrate_observable_estimates(qc, expt_results_as_obs, 
                                              symmetrization_method=exhaustive_symmetrization,
                                             num_shots=100):
    print(cal_res)
    print(f'Original expectation was {cal_res.raw_expectation}')
    print(f'Observable cal expectation was {cal_res.calibration_expectation} \n')

X0_0→(1+0j)*X0: 0.4651162790697675 +- 0.33757331148016795
Original expectation was 0.4
Observable cal expectation was 0.86 

X0_0→(1+0j)*Y0: -0.44943820224719105 +- 0.3260556713675604
Original expectation was -0.4
Observable cal expectation was 0.89 

X0_0→(1+0j)*Z0: 0.24096385542168677 +- 0.3734751606183784
Original expectation was 0.2
Observable cal expectation was 0.83 

